name: Continuous Integration
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Google Container Registry
        run: echo "${{ secrets.GCP_CREDENTIALS }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build, tag, and push image to Google Container Registry
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCR_REPOSITORY: nodejs-app
          IMAGE_TAG: latest
        run: |
          docker buildx build --platform linux/amd64 -t gcr.io/$GCP_PROJECT/$GCR_REPOSITORY:$IMAGE_TAG .
          docker push gcr.io/$GCP_PROJECT/$GCR_REPOSITORY:$IMAGE_TAG
